/**
 * Orialis Halo 02 volume renderer, adapted from the offline motion-study shader.
 * The caller owns animation scheduling and supplies the camera/frame state.
 * No DOM controls, assets, network access, or third-party libraries are used.
 */

const VERTEX = `#version 300 es
precision highp float;
out vec2 vUv;
void main(){ vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2); vUv=p; gl_Position=vec4(p*2.0-1.0,0.0,1.0); }`;

const SCENE = `#version 300 es
precision highp float;
in vec2 vUv;
out vec4 outColor;
uniform vec2 uResolution;
uniform vec2 uOffset;
uniform float uTime,uMotion,uEnergy,uState,uLight,uYaw,uPitch,uDistance,uSatelliteFocus;
uniform vec3 uSat0,uSat1,uSat2;
uniform int uMaxSteps;
const vec3 BLUE=vec3(.22,.43,1.0), ICE=vec3(.28,.66,1.0), LILAC=vec3(.53,.23,1.0), PEARL=vec3(.85,.91,1.0), GOLD=vec3(1.0,.68,.35);
mat3 rx(float a){float c=cos(a),s=sin(a);return mat3(1,0,0,0,c,s,0,-s,c);}
mat3 ry(float a){float c=cos(a),s=sin(a);return mat3(c,0,-s,0,1,0,s,0,c);}
mat3 rz(float a){float c=cos(a),s=sin(a);return mat3(c,s,0,-s,c,0,0,0,1);}
float sq(float x){return x*x;}
float wave(vec3 q,float t){return .135*sin(q.x*2.8+t*.29)*sin(q.y*3.4-t*.38)+.105*sin(q.z*3.3+t*.26)*cos(q.x*3.1-t*.2)+.048*sin(q.y*5.2+q.z*3.5+t*.38);}
vec3 waveGrad(vec3 q,float t){return vec3(.378*cos(q.x*2.8+t*.29)*sin(q.y*3.4-t*.38)-.3255*sin(q.z*3.3+t*.26)*sin(q.x*3.1-t*.2),.459*sin(q.x*2.8+t*.29)*cos(q.y*3.4-t*.38)+.2496*cos(q.y*5.2+q.z*3.5+t*.38),.3465*cos(q.z*3.3+t*.26)*cos(q.x*3.1-t*.2)+.168*cos(q.y*5.2+q.z*3.5+t*.38));}
vec3 sheen(vec3 n,vec3 rd,float t,float hue){float rim=pow(1.0-abs(dot(n,rd)),2.35);vec3 refl=reflect(rd,n);float softbox=pow(max(dot(refl,normalize(vec3(-.6,.8,1.2))),0.0),22.0);float strip=pow(max(dot(refl,normalize(vec3(.9,-.6,.5))),0.0),36.0);float lower=pow(max(dot(refl,normalize(vec3(-.3,-1.0,.4))),0.0),15.0);float irid=.5+.5*sin(dot(n,normalize(vec3(.7,1.,.4)))*4.2+hue+t*.06);return mix(ICE,LILAC,irid*.8)*(.14+rim*.93)+PEARL*softbox*1.7+GOLD*strip*.40+ICE*lower*.62;}
void addMedium(inout vec4 m,vec3 col,float sigma){m.rgb+=col*sigma;m.a+=sigma;}
float sdBox2(vec2 p,vec2 b){vec2 q=abs(p)-b;return length(max(q,0.))+min(max(q.x,q.y),0.);}
void ribbon(inout vec4 medium,inout float nearD,vec3 p,vec3 rd,float t,float which){float tt=t*(.38+.11*uEnergy);mat3 basis=rz(mix(-.22,1.08,which)+.075*sin(tt*.27+which*3.))*rx(mix(1.06,1.30,which)+.12*sin(tt*.35+which*2.1))*ry(.13*sin(tt*.21+which));vec3 q=transpose(basis)*p;float theta=atan(q.y,q.x),r=length(q.xy),phase=theta-tt*(1.0+which*.21);float target=mix(1.55,1.74,which)+.075*sin(theta*3.-tt*.66+which)+.07*cos(theta*2.+tt*.44);float rise=.13*sin(theta*2.+tt*.9+which*2.5)+.055*cos(theta*3.-tt*.6);float roll=.35+.72*sin(theta+tt*.53+which*2.)+.30*cos(theta*2.-tt*.27);float cs=cos(roll),sn=sin(roll);vec2 uv=mat2(cs,-sn,sn,cs)*vec2(r-target,q.z-rise);float crest=pow(.5+.5*cos(phase+which*2.),5.0);float width=(mix(.084,.069,which)+.077*crest+.018*sin(phase*2.+1.))*(.87+uEnergy*.35);float thickness=mix(.018,.015,which)+.009*crest;float d=sdBox2(uv,vec2(width,thickness))-.012;nearD=min(nearD,max(abs(d)*.72,.003));if(d>.12)return;float inside=1.-smoothstep(-.012,.025,d),veil=exp(-max(d,0.)*70.)*.65,edge=pow(clamp(abs(uv.x)/(width+.012),0.,1.),5.);vec2 cn=normalize(vec2(uv.x/sq(width+.012),uv.y/sq(thickness+.012)));vec2 un=mat2(cs,sn,-sn,cs)*cn;vec3 n=basis*vec3(un.x*cos(theta),un.x*sin(theta),un.y);vec3 col=sheen(n,rd,t,which*2.0)*.49;vec3 tint=mix(vec3(.23,.58,1.),vec3(.53,.30,.98),which);col+=tint*.26+PEARL*edge*(.28+crest*.35);col=mix(col,col+GOLD*(.55+edge)*crest,.18+uState*.10);col+=PEARL*pow(crest,3.)*(.08+uEnergy*.10);addMedium(medium,col,(inside*13.0+veil*1.3)*(.72+uEnergy*.18));}
void satellite(inout vec4 medium,inout float nearD,vec3 p,vec3 rd,vec3 center,float rad,vec3 tint,float focus){vec3 q=p-center;float len=length(q),d=len-rad;nearD=min(nearD,max(abs(d)*.75,.004));if(d>.24)return;float body=1.-smoothstep(-.007,.019,d);vec3 n=q/max(len,.001);vec3 col=tint*.60+PEARL*pow(max(dot(n,normalize(vec3(-1.,1.,2.))),0.),4.)*1.1;col+=PEARL*pow(1.-abs(dot(n,rd)),2.)*.35;addMedium(medium,col,body*56.);float glow=exp(-max(d,0.)*33.)*(1.-body);addMedium(medium,tint*(1.6+focus*2.2),glow*(1.1+focus*1.4));}
vec4 field(vec3 p,vec3 rd,float t,out float nearD){vec4 medium=vec4(0.);nearD=.3;float radius=length(p);if(radius<1.57){float breathe=1.+.032*sin(t*.9)+.024*uState*sin(t*2.3);mat3 basis=rz(.17*sin(t*.18))*ry(.19*sin(t*.23));vec3 q=transpose(basis)*p/(breathe*1.06);q-=vec3(.06*sin(q.y*2.+t*.35),.035*cos(q.z*2.2+t*.28),.065*sin(q.x*2.4-t*.28));float amp=.7+uMotion*.9;vec3 axes=vec3(.83,1.01,.87);float d=length(q/axes)-1.+wave(q,t)*amp;vec3 n=basis*normalize(q/(axes*axes)+waveGrad(q,t)*amp);vec3 qi=ry(.54+t*.07)*q+vec3(.10*sin(t*.21),-.055,.025);float d2=length(qi/vec3(.65,.76,.66))-1.+wave(qi*1.16,t+2.)*(.85+uMotion*.8);vec3 ni=basis*ry(-.54-t*.07)*normalize(qi/vec3(.4225,.5776,.4356)+waveGrad(qi*1.16,t+2.)*.85);vec3 qj=rz(-.6-t*.055)*q+vec3(-.13,.035,.06);float d3=length(qj/vec3(.46,.61,.51))-1.+wave(qj*1.3,t+5.)*1.55;vec3 nj=basis*rz(.6+t*.055)*normalize(qj/vec3(.2116,.3721,.2601)+waveGrad(qj*1.3,t+5.));nearD=min(nearD,min(abs(d)*.62,min(abs(d2)*.42,abs(d3)*.30)));float membrane=exp(-abs(d)*82.),middle=exp(-abs(d2)*67.),inner=exp(-abs(d3)*54.);float clarityDensity=.574;addMedium(medium,sheen(n,rd,t,0.)+BLUE*.08,membrane*13.*clarityDensity);addMedium(medium,sheen(ni,rd,t,2.2)*.83+LILAC*.15,middle*11.*clarityDensity);addMedium(medium,sheen(nj,rd,t,3.8)*.8+ICE*.23,inner*9.*clarityDensity);float cloud=exp(-dot(q*vec3(1.1,1.,1.2),q*vec3(1.1,1.,1.2))*3.1);vec3 cloudTint=mix(BLUE,LILAC,.5+.4*sin(q.y*2.3+t*.21));addMedium(medium,cloudTint*.83,cloud*.448);vec3 heart=q-vec3(-.12+.07*sin(t*.3),-.18,.12);float flame=exp(-dot(heart/vec3(.28,.34,.3),heart/vec3(.28,.34,.3))*1.7);addMedium(medium,mix(ICE,PEARL,.58)*2.,flame*.95);}if(radius>1.2&&radius<2.48)ribbon(medium,nearD,p,rd,t,0.);if(radius>1.3&&radius<2.52)ribbon(medium,nearD,p,rd,t,1.);float focusSchedule=1.-step(.5,abs(uSatelliteFocus-1.));float focusNews=1.-step(.5,abs(uSatelliteFocus-2.));satellite(medium,nearD,p,rd,uSat0,.087,vec3(.63,.83,1.),focusSchedule);satellite(medium,nearD,p,rd,uSat1,.073,vec3(.85,.70,1.),focusNews);satellite(medium,nearD,p,rd,uSat2,.10,vec3(1.,.78,.48),0.);if(medium.a>.0001)medium.rgb/=medium.a;return medium;}
void main(){vec2 screen=(gl_FragCoord.xy*2.-uResolution)/uResolution.y;screen-=uOffset;vec3 ro=uDistance*vec3(sin(uYaw)*cos(uPitch),sin(uPitch),cos(uYaw)*cos(uPitch));vec3 forward=normalize(-ro),right=normalize(cross(forward,vec3(0,1,0))),up=cross(right,forward);vec3 rd=normalize(right*screen.x+up*screen.y+forward*3.);float b=dot(ro,rd),c=dot(ro,ro)-9.30,h=b*b-c;vec3 acc=vec3(0.);float trans=1.;if(h>=0.){h=sqrt(h);float t=max(0.,-b-h),endT=-b+h;for(int i=0;i<160;i++){if(i>=uMaxSteps||t>endT||trans<.009)break;float nearD;vec4 sampleValue=field(ro+rd*t,rd,uTime,nearD);float stepLength=clamp(nearD*.66,.018,.145);float a=1.-exp(-sampleValue.a*stepLength);acc+=trans*a*sampleValue.rgb;trans*=1.-a;t+=stepLength;}}outColor=vec4(acc,1.-trans);}`;

const BLUR = `#version 300 es
precision highp float;
in vec2 vUv;out vec4 outColor;uniform sampler2D uImage;uniform vec2 uDirection;uniform float uExtract;
vec4 readColor(vec2 uv){vec4 c=texture(uImage,uv);if(uExtract>.5){float l=max(c.r,max(c.g,c.b));c.rgb*=smoothstep(.38,.85,l);}return c;}
void main(){vec4 col=readColor(vUv)*.2270270270;col+=readColor(vUv+uDirection*1.3846153846)*.3162162162;col+=readColor(vUv-uDirection*1.3846153846)*.3162162162;col+=readColor(vUv+uDirection*3.2307692308)*.0702702703;col+=readColor(vUv-uDirection*3.2307692308)*.0702702703;outColor=col;}`;

const COMPOSITE = `#version 300 es
precision highp float;in vec2 vUv;out vec4 outColor;uniform sampler2D uScene,uBloom,uWide;uniform float uLight;
void main(){vec4 s=texture(uScene,vUv),b=texture(uBloom,vUv),w=texture(uWide,vUv);vec3 radiance=s.rgb+b.rgb*mix(.19,.055,uLight)+w.rgb*mix(.11,.035,uLight);float a=clamp(s.a+b.a*.34+w.a*.18,0.,1.);vec3 straight=radiance/max(a,.0001);vec3 mapped=clamp((straight*(2.51*straight+.03))/(straight*(2.43*straight+.59)+.14),0.,1.);vec3 halo=pow(mapped,vec3(1./2.2))*a;vec3 dark=vec3(5.,9.,19.)/255.;vec3 light=vec3(243.,242.,238.)/255.;vec3 bgLinear=mix(pow(dark,vec3(2.2)),vec3(.8963,.8880,.8632),uLight);vec3 bg=pow(bgLinear,vec3(1./2.2));if(uLight>=1.)bg=light;outColor=vec4(halo+bg*(1.-a),1.);}`;

const DEFAULTS = Object.freeze({time:5.3,yaw:.13,pitch:.07,distance:8.6,light:0,offsetX:0,offsetY:0,energy:.72,motion:.84,state:0,quality:.7,satelliteFocus:0});
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
function rotateOrbit(a,inc,azimuth,r,ellipticity=1){const x=r*Math.cos(a),y=r*ellipticity*Math.sin(a)*Math.cos(inc),z=r*ellipticity*Math.sin(a)*Math.sin(inc);return [x*Math.cos(azimuth)-y*Math.sin(azimuth),x*Math.sin(azimuth)+y*Math.cos(azimuth),z];}

/** Create an independently disposable renderer on a canvas. Returns null on unsupported or failed WebGL2. */
export function createHalo(canvas){
  if(!canvas||typeof canvas.getContext!=='function')return null;
  let gl;try{gl=canvas.getContext('webgl2',{alpha:true,antialias:false,powerPreference:'high-performance',premultipliedAlpha:true});}catch{return null;}
  if(!gl)return null;
  let programs=[],targets=[],vao=null,disposed=false,lost=false,renderCount=0,lastRenderMs=0,lastFrame={...DEFAULTS},width=0,height=0,renderWidth=0,renderHeight=0,error='';
  const setError=(value)=>{error=String(value||'WebGL2 renderer error');try{canvas.dataset.haloError=error;}catch{};};
  const compile=(type,source)=>{const shader=gl.createShader(type);if(!shader)throw new Error('Unable to allocate shader');gl.shaderSource(shader,source);gl.compileShader(shader);if(!gl.getShaderParameter(shader,gl.COMPILE_STATUS)){const message=gl.getShaderInfoLog(shader)||'unknown shader compilation error';gl.deleteShader(shader);throw new Error(message);}return shader;};
  const makeProgram=(fragment)=>{let vs,fs,p,registered=false;try{vs=compile(gl.VERTEX_SHADER,VERTEX);fs=compile(gl.FRAGMENT_SHADER,fragment);p=gl.createProgram();if(!p)throw new Error('Unable to allocate program');gl.attachShader(p,vs);gl.attachShader(p,fs);gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)||'program link failed');const cache=new Map();const result={p,u:(name)=>{if(!cache.has(name))cache.set(name,gl.getUniformLocation(p,name));return cache.get(name);}};programs.push(result);registered=true;return result;}finally{if(vs)gl.deleteShader(vs);if(fs)gl.deleteShader(fs);if(p&&!registered)gl.deleteProgram(p);}};
  const freeTarget=(t)=>{if(!t)return;if(t.texture)gl.deleteTexture(t.texture);if(t.fb)gl.deleteFramebuffer(t.fb);};
  const freeTargets=()=>{targets.forEach(freeTarget);targets=[];};
  let floatTargets=!!gl.getExtension('EXT_color_buffer_float');
  const allocateTarget=(w,h)=>{const texture=gl.createTexture(),fb=gl.createFramebuffer();if(!texture||!fb){if(texture)gl.deleteTexture(texture);if(fb)gl.deleteFramebuffer(fb);throw new Error('Unable to allocate render target');}const configure=(floating)=>{gl.bindTexture(gl.TEXTURE_2D,texture);gl.texImage2D(gl.TEXTURE_2D,0,floating?gl.RGBA16F:gl.RGBA8,w,h,0,gl.RGBA,floating?gl.HALF_FLOAT:gl.UNSIGNED_BYTE,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.bindFramebuffer(gl.FRAMEBUFFER,fb);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,texture,0);return gl.checkFramebufferStatus(gl.FRAMEBUFFER)===gl.FRAMEBUFFER_COMPLETE;};let ok=configure(floatTargets);if(!ok&&floatTargets){floatTargets=false;ok=configure(false);}if(!ok){gl.deleteTexture(texture);gl.deleteFramebuffer(fb);throw new Error('Framebuffer allocation failed');}return {texture,fb,w,h};};
  const sizeTargets=()=>{const rect=canvas.getBoundingClientRect(),cssW=Math.max(1,rect.width||canvas.clientWidth||1),cssH=Math.max(1,rect.height||canvas.clientHeight||1),portrait=cssH>cssW;const capW=portrait?540:900,capH=portrait?840:720;const dpr=Math.min(globalThis.devicePixelRatio||1,1.5);const scale=Math.min(dpr,capW/cssW,capH/cssH);const rawW=Math.max(2,Math.round(cssW*scale)),rawH=Math.max(2,Math.round(cssH*scale));const q=clamp(Number(lastFrame.quality)||0,0.25,1);const rw=Math.max(2,Math.round(rawW*q)),rh=Math.max(2,Math.round(rawH*q));if(width===rawW&&height===rawH&&renderWidth===rw&&renderHeight===rh&&targets.length)return;freeTargets();width=rawW;height=rawH;renderWidth=rw;renderHeight=rh;canvas.width=rawW;canvas.height=rawH;const halfW=Math.max(2,rw>>1),halfH=Math.max(2,rh>>1),quarterW=Math.max(2,rw>>2),quarterH=Math.max(2,rh>>2);const nextTargets=[];try{nextTargets.push(allocateTarget(rw,rh));nextTargets.push(allocateTarget(halfW,halfH));nextTargets.push(allocateTarget(halfW,halfH));nextTargets.push(allocateTarget(quarterW,quarterH));nextTargets.push(allocateTarget(quarterW,quarterH));targets=nextTargets;}catch(e){nextTargets.forEach(freeTarget);throw e;}};
  const bindTexture=(p,name,texture,slot)=>{gl.activeTexture(gl.TEXTURE0+slot);gl.bindTexture(gl.TEXTURE_2D,texture);gl.uniform1i(p.u(name),slot);};
  const pass=(p,target)=>{gl.useProgram(p.p);gl.bindFramebuffer(gl.FRAMEBUFFER,target?target.fb:null);gl.viewport(0,0,target?target.w:canvas.width,target?target.h:canvas.height);};
  const draw=()=>gl.drawArrays(gl.TRIANGLES,0,3);
  let scene,blur,composite;
  const onLost=(event)=>{event.preventDefault();lost=true;setError('WebGL2 context lost.');};
  canvas.addEventListener('webglcontextlost',onLost,false);
  try{scene=makeProgram(SCENE);blur=makeProgram(BLUR);composite=makeProgram(COMPOSITE);vao=gl.createVertexArray();if(!vao)throw new Error('Unable to allocate vertex array');gl.bindVertexArray(vao);gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.pixelStorei(gl.UNPACK_ALIGNMENT,1);}catch(e){setError(e?.message||e);programs.forEach((p)=>gl.deleteProgram(p.p));canvas.removeEventListener('webglcontextlost',onLost);return null;}
  const render=(frame={})=>{if(disposed||lost)return;const next={...DEFAULTS,...frame};for(const key of Object.keys(DEFAULTS))if(!Number.isFinite(Number(next[key])))next[key]=DEFAULTS[key];next.light=clamp(next.light,0,1);next.energy=clamp(next.energy,0,1);next.motion=clamp(next.motion,0,1);next.state=clamp(next.state,0,2);next.quality=clamp(next.quality,.25,1);next.satelliteFocus=clamp(next.satelliteFocus,0,2);lastFrame=next;const started=globalThis.performance?.now?.()??Date.now();try{sizeTargets();const [main,b0,b1,w0,w1]=targets;gl.bindVertexArray(vao);pass(scene,main);gl.uniform2f(scene.u('uResolution'),main.w,main.h);gl.uniform2f(scene.u('uOffset'),next.offsetX,next.offsetY);for(const [key,value] of Object.entries({uTime:next.time,uMotion:next.motion,uEnergy:next.energy,uState:next.state,uLight:next.light,uYaw:next.yaw,uPitch:next.pitch,uDistance:next.distance*Math.max(1,1.08/(main.w/main.h)),uSatelliteFocus:next.satelliteFocus}))gl.uniform1f(scene.u(key),value);gl.uniform1i(scene.u('uMaxSteps'),144);gl.uniform3fv(scene.u('uSat0'),rotateOrbit(next.time*.24+.10,1.11,-.39,2.23,.91));gl.uniform3fv(scene.u('uSat1'),rotateOrbit(-next.time*.175+2.10,.89,1.02,2.33,.87));gl.uniform3fv(scene.u('uSat2'),rotateOrbit(next.time*.14+4.8,1.21,-.14,2.52,.95));draw();const blit=(out,src,x,y,extract=0)=>{pass(blur,out);bindTexture(blur,'uImage',src.texture,0);gl.uniform2f(blur.u('uDirection'),x/src.w,y/src.h);gl.uniform1f(blur.u('uExtract'),extract);draw();};blit(b0,main,2.8,0,1);blit(b1,b0,0,2.8);blit(w0,b1,3.5,0);blit(w1,w0,0,3.5);pass(composite,null);bindTexture(composite,'uScene',main.texture,0);bindTexture(composite,'uBloom',b1.texture,1);bindTexture(composite,'uWide',w1.texture,2);gl.uniform1f(composite.u('uLight'),next.light);draw();renderCount++;lastRenderMs=(globalThis.performance?.now?.()??Date.now())-started;error='';if(canvas.dataset)delete canvas.dataset.haloError;}catch(e){setError(e?.message||e);lastRenderMs=(globalThis.performance?.now?.()??Date.now())-started;}};
  const dispose=()=>{if(disposed)return;disposed=true;canvas.removeEventListener('webglcontextlost',onLost);freeTargets();programs.forEach((p)=>gl.deleteProgram(p.p));programs=[];if(vao)gl.deleteVertexArray(vao);vao=null;const lose=gl.getExtension('WEBGL_lose_context');if(lose)lose.loseContext();};
  const stats=()=>({size:{width:width,height:height,renderWidth:renderWidth,renderHeight:renderHeight},renders:renderCount,lastRenderMs:Number(lastRenderMs.toFixed(2)),error:error||null});
  return {render,dispose,stats};
}
