-- Orialis first-round core schema.
--
-- All timestamps are UTC ISO-8601 strings. IDs are UUID strings generated by
-- the service. Version is an optimistic-concurrency version and starts at 1.
-- Sync writes should append to sync_events in the same transaction as the
-- entity mutation. Deleted entities remain addressable through deleted_at so
-- downstream clients can receive tombstones.

PRAGMA foreign_keys = ON;

CREATE TABLE users (
    id TEXT NOT NULL PRIMARY KEY,
    username TEXT NOT NULL COLLATE NOCASE UNIQUE,
    password_hash TEXT NOT NULL,
    display_name TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0)
);

CREATE TABLE user_sessions (
    id TEXT NOT NULL PRIMARY KEY,
    user_id TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    last_seen_at TEXT,
    revoked_at TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_user_sessions_user_active
    ON user_sessions (user_id, revoked_at, expires_at);

CREATE TABLE projects (
    id TEXT NOT NULL PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    goal TEXT,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'completed', 'archived')),
    start_date TEXT,
    due TEXT,
    color TEXT,
    next_action_task_id TEXT,
    deleted_at TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_projects_user_updated
    ON projects (user_id, updated_at, id);

CREATE INDEX idx_projects_user_active
    ON projects (user_id, deleted_at, status);

CREATE TABLE tasks (
    id TEXT NOT NULL PRIMARY KEY,
    user_id TEXT NOT NULL,
    project_id TEXT,
    title TEXT NOT NULL,
    notes TEXT,
    task_type TEXT NOT NULL DEFAULT 'task'
        CHECK (task_type IN ('assignment', 'project', 'daily', 'task')),
    important INTEGER NOT NULL DEFAULT 0 CHECK (important IN (0, 1)),
    urgent INTEGER NOT NULL DEFAULT 0 CHECK (urgent IN (0, 1)),
    completed INTEGER NOT NULL DEFAULT 0 CHECK (completed IN (0, 1)),
    completed_at TEXT,
    due TEXT,
    due_time TEXT,
    recurrence_rule TEXT,
    recurrence_until TEXT,
    reminder_minutes INTEGER,
    source TEXT,
    deleted_at TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE SET NULL,
    CHECK (completed = 0 OR completed_at IS NOT NULL),
    CHECK (reminder_minutes IS NULL OR reminder_minutes >= 0)
);

CREATE INDEX idx_tasks_user_updated
    ON tasks (user_id, updated_at, id);

CREATE INDEX idx_tasks_user_active_due
    ON tasks (user_id, deleted_at, completed, due, due_time);

CREATE INDEX idx_tasks_project_active
    ON tasks (project_id, deleted_at, updated_at);

CREATE TABLE project_milestones (
    id TEXT NOT NULL PRIMARY KEY,
    project_id TEXT NOT NULL,
    title TEXT NOT NULL,
    due TEXT,
    completed INTEGER NOT NULL DEFAULT 0 CHECK (completed IN (0, 1)),
    completed_at TEXT,
    position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0),
    deleted_at TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE,
    CHECK (completed = 0 OR completed_at IS NOT NULL)
);

CREATE INDEX idx_project_milestones_project_position
    ON project_milestones (project_id, deleted_at, position, id);

CREATE TABLE calendar_events (
    id TEXT NOT NULL PRIMARY KEY,
    user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    location TEXT,
    start_at TEXT NOT NULL,
    end_at TEXT NOT NULL,
    all_day INTEGER NOT NULL DEFAULT 0 CHECK (all_day IN (0, 1)),
    reminder_minutes INTEGER,
    source TEXT,
    deleted_at TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CHECK (end_at >= start_at),
    CHECK (reminder_minutes IS NULL OR reminder_minutes >= 0)
);

CREATE INDEX idx_calendar_events_user_start
    ON calendar_events (user_id, deleted_at, start_at, end_at, id);

CREATE INDEX idx_calendar_events_user_updated
    ON calendar_events (user_id, updated_at, id);

CREATE TABLE sync_events (
    id TEXT NOT NULL PRIMARY KEY,
    user_id TEXT NOT NULL,
    cursor INTEGER NOT NULL CHECK (cursor > 0),
    entity_type TEXT NOT NULL
        CHECK (entity_type IN ('task', 'project', 'project_milestone', 'calendar_event')),
    entity_id TEXT NOT NULL,
    operation TEXT NOT NULL CHECK (operation IN ('upsert', 'delete')),
    entity_version INTEGER NOT NULL CHECK (entity_version > 0),
    tombstone INTEGER NOT NULL DEFAULT 0 CHECK (tombstone IN (0, 1)),
    payload_json TEXT,
    deleted_at TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CHECK (
        (operation = 'delete' AND tombstone = 1 AND deleted_at IS NOT NULL)
        OR
        (operation = 'upsert' AND tombstone = 0)
    )
);

CREATE UNIQUE INDEX uq_sync_events_user_cursor
    ON sync_events (user_id, cursor);

CREATE INDEX idx_sync_events_user_cursor
    ON sync_events (user_id, cursor, id);

CREATE INDEX idx_sync_events_entity
    ON sync_events (user_id, entity_type, entity_id, cursor);
